//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XMLGuideImporter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GrabberCommandLine {
            get {
                return ((string)(this["GrabberCommandLine"]));
            }
            set {
                this["GrabberCommandLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XMLTVPath {
            get {
                return ((string)(this["XMLTVPath"]));
            }
            set {
                this["XMLTVPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GrabberArguments {
            get {
                return ((string)(this["GrabberArguments"]));
            }
            set {
                this["GrabberArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("display-name[position()=2]/text()")]
        public string ChannelNumberXPath {
            get {
                return ((string)(this["ChannelNumberXPath"]));
            }
            set {
                this["ChannelNumberXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("display-name[position()=3]/text()")]
        public string CallsignXPath {
            get {
                return ((string)(this["CallsignXPath"]));
            }
            set {
                this["CallsignXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("display-name[position()=4]/text()")]
        public string ServiceNameXPath {
            get {
                return ((string)(this["ServiceNameXPath"]));
            }
            set {
                this["ServiceNameXPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XMLImportedLineup1")]
        public string MXFLineupUid {
            get {
                return ((string)(this["MXFLineupUid"]));
            }
            set {
                this["MXFLineupUid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("XML Imported Lineup")]
        public string MXFLineupName {
            get {
                return ((string)(this["MXFLineupName"]));
            }
            set {
                this["MXFLineupName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("display-name[position()=5]/text()")]
        public string AffiliateXPath {
            get {
                return ((string)(this["AffiliateXPath"]));
            }
            set {
                this["AffiliateXPath"] = value;
            }
        }
    }
}
